name: Build with gcc and run

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Run
      run: make run
